name = "web3"
version = "0.1.0"
license = "license"
author = "Andre Smit"
maintainer = "freevryheid@gmail.com"
copyright = "Copyright 2023, Andre Smit"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
